/**
 * Asian RTD Beverage Ingredient Database
 * Comprehensive mock database with realistic food science properties
 * MoBai R&D Platform
 */

import type { Ingredient } from './types';

export const ASIAN_RTD_INGREDIENTS: Ingredient[] = [
  // ===== BASE LIQUIDS =====
  {
    id: 'WTR_001',
    name: 'Purified Water',
    nameChinese: '纯净水',
    category: 'base-liquid',
    function: ['solvent', 'diluent', 'volume-filler'],
    properties: {
      solubility: 'water-soluble',
      pHStabilityMin: 5.5,
      pHStabilityMax: 8.5,
      heatSensitivity: 'low',
      maxProcessingTemp: 150,
      storageTemp: 'Ambient (15-25°C)',
      shelfLifeMonths: 120,
      caloriesPer100g: 0,
      proteinPer100g: 0,
      sugarPer100g: 0,
    },
    suppliers: [
      { name: 'Nongfu Spring', location: 'Hangzhou, China', country: 'China', moqKg: 500, leadTimeDays: 7, costPerKg: 0.15, certifications: ['ISO 22000', 'CNAS', 'FDA Registered'], reliability: 0.98, inStock: true },
      { name: 'Suntory', location: 'Osaka, Japan', country: 'Japan', moqKg: 1000, leadTimeDays: 14, costPerKg: 0.22, certifications: ['JIS Q 9001', 'FSSC 22000'], reliability: 0.99, inStock: true },
    ],
    substitutes: [],
    regulatoryStatus: { fda: 'approved', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },
  {
    id: 'COC_001',
    name: 'Coconut Water Concentrate',
    nameChinese: '椰子水浓缩液',
    category: 'base-liquid',
    function: ['hydration', 'electrolytes', 'natural-flavor'],
    properties: {
      solubility: 'water-soluble',
      pHStabilityMin: 4.0,
      pHStabilityMax: 5.5,
      heatSensitivity: 'medium',
      maxProcessingTemp: 95,
      storageTemp: 'Chilled (2-8°C)',
      shelfLifeMonths: 6,
      caloriesPer100g: 18,
      proteinPer100g: 0.5,
      sugarPer100g: 4.0,
    },
    suppliers: [
      { name: 'Thai Coconut', location: 'Phuket, Thailand', country: 'Thailand', moqKg: 200, leadTimeDays: 21, costPerKg: 4.80, certifications: ['ISO 22000', 'USDA Organic', 'FDA Registered'], reliability: 0.92, inStock: true },
      { name: 'PT Bali Cocofarm', location: 'Bali, Indonesia', country: 'Indonesia', moqKg: 500, leadTimeDays: 28, costPerKg: 4.20, certifications: ['ISO 22000', 'HACCP'], reliability: 0.88, inStock: false },
    ],
    substitutes: ['ALO_001'],
    regulatoryStatus: { fda: 'approved', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },

  // ===== PROTEIN SOURCES =====
  {
    id: 'PRO_001',
    name: 'Whey Protein Isolate 90',
    nameChinese: '乳清蛋白分离物 90',
    category: 'protein-source',
    function: ['protein-enrichment', 'texture-enhancement', 'mouthfeel'],
    properties: {
      solubility: 'water-soluble',
      pHStabilityMin: 3.5,
      pHStabilityMax: 6.5,
      heatSensitivity: 'medium',
      maxProcessingTemp: 75,
      storageTemp: 'Cool & Dry (<25°C)',
      shelfLifeMonths: 24,
      caloriesPer100g: 375,
      proteinPer100g: 90,
      sugarPer100g: 1.0,
    },
    suppliers: [
      { name: 'FrieslandCampina', location: 'Amersfoort, Netherlands', country: 'Singapore', moqKg: 100, leadTimeDays: 14, costPerKg: 18.50, certifications: ['FSSC 22000', 'FDA GRAS', 'ISO 9001'], reliability: 0.97, inStock: true },
      { name: 'Milei GmbH', location: 'Leipzig, Germany', country: 'Singapore', moqKg: 250, leadTimeDays: 21, costPerKg: 17.80, certifications: ['ISO 22000', 'FDA GRAS'], reliability: 0.95, inStock: true },
    ],
    substitutes: ['PRO_002', 'PRO_003'],
    regulatoryStatus: { fda: 'gras', efsa: 'approved', chinaGB: 'approved' },
    allergens: ['Milk'],
  },
  {
    id: 'PRO_002',
    name: 'Soy Protein Isolate',
    nameChinese: '大豆蛋白分离物',
    category: 'protein-source',
    function: ['protein-enrichment', 'texture-enhancement'],
    properties: {
      solubility: 'water-soluble',
      pHStabilityMin: 4.0,
      pHStabilityMax: 8.0,
      heatSensitivity: 'low',
      maxProcessingTemp: 121,
      storageTemp: 'Cool & Dry (<25°C)',
      shelfLifeMonths: 18,
      caloriesPer100g: 338,
      proteinPer100g: 88,
      sugarPer100g: 0,
    },
    suppliers: [
      { name: 'Cargill', location: 'Shanghai, China', country: 'China', moqKg: 500, leadTimeDays: 14, costPerKg: 8.50, certifications: ['ISO 22000', 'Non-GMO', 'FDA GRAS'], reliability: 0.96, inStock: true },
      { name: 'DuPont Nutrition', location: 'Copenhagen, Denmark', country: 'Singapore', moqKg: 200, leadTimeDays: 21, costPerKg: 9.20, certifications: ['ISO 22000', 'Non-GMO Project'], reliability: 0.98, inStock: true },
    ],
    substitutes: ['PRO_001', 'PRO_003'],
    regulatoryStatus: { fda: 'gras', efsa: 'approved', chinaGB: 'approved' },
    allergens: ['Soy'],
  },
  {
    id: 'PRO_003',
    name: 'Pea Protein Isolate 85',
    nameChinese: '豌豆蛋白分离物 85',
    category: 'protein-source',
    function: ['protein-enrichment', 'plant-based-alternative'],
    properties: {
      solubility: 'water-soluble',
      pHStabilityMin: 4.5,
      pHStabilityMax: 8.5,
      heatSensitivity: 'low',
      maxProcessingTemp: 121,
      storageTemp: 'Cool & Dry (<25°C)',
      shelfLifeMonths: 24,
      caloriesPer100g: 360,
      proteinPer100g: 85,
      sugarPer100g: 0,
    },
    suppliers: [
      { name: 'Roquette', location: 'Lestrem, France', country: 'Singapore', moqKg: 300, leadTimeDays: 18, costPerKg: 12.50, certifications: ['ISO 22000', 'FDA GRAS', 'Organic'], reliability: 0.94, inStock: true },
      { name: 'COSUCRA', location: 'Warcoing, Belgium', country: 'Singapore', moqKg: 200, leadTimeDays: 21, costPerKg: 11.80, certifications: ['ISO 22000', 'Non-GMO'], reliability: 0.93, inStock: true },
    ],
    substitutes: ['PRO_001', 'PRO_002'],
    regulatoryStatus: { fda: 'gras', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },

  // ===== SWEETENERS =====
  {
    id: 'SWT_001',
    name: 'Erythritol',
    nameChinese: '赤藓糖醇',
    category: 'sweetener',
    function: ['sweetening', 'sugar-reduction', 'cooling-effect'],
    properties: {
      solubility: 'water-soluble',
      pHStabilityMin: 2.0,
      pHStabilityMax: 10.0,
      heatSensitivity: 'low',
      maxProcessingTemp: 160,
      storageTemp: 'Cool & Dry',
      shelfLifeMonths: 36,
      caloriesPer100g: 0,
      proteinPer100g: 0,
      sugarPer100g: 0,
    },
    suppliers: [
      { name: 'Bolasia', location: 'Shandong, China', country: 'China', moqKg: 500, leadTimeDays: 14, costPerKg: 4.20, certifications: ['ISO 22000', 'FDA GRAS', 'EU Novel Food'], reliability: 0.95, inStock: true },
      { name: 'Jungbunzlauer', location: 'Vienna, Austria', country: 'Singapore', moqKg: 1000, leadTimeDays: 21, costPerKg: 5.80, certifications: ['ISO 22000', 'Kosher', 'Halal'], reliability: 0.98, inStock: true },
    ],
    substitutes: ['SWT_002', 'SWT_003'],
    regulatoryStatus: { fda: 'approved', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },
  {
    id: 'SWT_002',
    name: 'Stevia Reb-M 97%',
    nameChinese: '甜菊糖 Reb-M 97%',
    category: 'sweetener',
    function: ['high-intensity-sweetening', 'sugar-reduction', 'non-caloric'],
    properties: {
      solubility: 'water-soluble',
      pHStabilityMin: 3.0,
      pHStabilityMax: 8.0,
      heatSensitivity: 'low',
      maxProcessingTemp: 150,
      storageTemp: 'Cool & Dry',
      shelfLifeMonths: 48,
      caloriesPer100g: 0,
      proteinPer100g: 0,
      sugarPer100g: 0,
    },
    suppliers: [
      { name: 'GLG Life Tech', location: 'Hefei, China', country: 'China', moqKg: 10, leadTimeDays: 14, costPerKg: 850.00, certifications: ['ISO 22000', 'FDA GRAS', 'EFSA'], reliability: 0.94, inStock: true },
      { name: ' Ingredion', location: 'Illinois, USA', country: 'Singapore', moqKg: 25, leadTimeDays: 21, costPerKg: 920.00, certifications: ['ISO 22000', 'FDA GRAS'], reliability: 0.97, inStock: true },
    ],
    substitutes: ['SWT_001', 'SWT_003'],
    regulatoryStatus: { fda: 'approved', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },
  {
    id: 'SWT_003',
    name: 'Allulose',
    nameChinese: '阿洛酮糖',
    category: 'sweetener',
    function: ['sweetening', 'sugar-reduction', 'browning-agent'],
    properties: {
      solubility: 'water-soluble',
      pHStabilityMin: 2.0,
      pHStabilityMax: 9.0,
      heatSensitivity: 'low',
      maxProcessingTemp: 150,
      storageTemp: 'Cool & Dry',
      shelfLifeMonths: 24,
      caloriesPer100g: 4,
      proteinPer100g: 0,
      sugarPer100g: 90,
    },
    suppliers: [
      { name: 'CJ Bio', location: 'Seoul, Korea', country: 'Korea', moqKg: 100, leadTimeDays: 21, costPerKg: 12.50, certifications: ['ISO 22000', 'FDA GRAS', 'Korean FDA'], reliability: 0.96, inStock: true },
      { name: 'Mitsubishi Chemical', location: 'Tokyo, Japan', country: 'Japan', moqKg: 200, leadTimeDays: 28, costPerKg: 14.80, certifications: ['ISO 22000', 'FDA GRAS'], reliability: 0.95, inStock: false },
    ],
    substitutes: ['SWT_001', 'SWT_002'],
    regulatoryStatus: { fda: 'approved', efsa: 'pending', chinaGB: 'approved' },
    allergens: [],
  },

  // ===== ACIDULANTS =====
  {
    id: 'ACD_001',
    name: 'Citric Acid Anhydrous',
    nameChinese: '无水柠檬酸',
    category: 'acidulant',
    function: ['acidulation', 'flavor-enhancement', 'preservation'],
    properties: {
      solubility: 'water-soluble',
      pHStabilityMin: 2.0,
      pHStabilityMax: 6.5,
      heatSensitivity: 'low',
      maxProcessingTemp: 150,
      storageTemp: 'Cool & Dry',
      shelfLifeMonths: 36,
      caloriesPer100g: 0,
      proteinPer100g: 0,
      sugarPer100g: 0,
    },
    suppliers: [
      { name: 'Runcang', location: 'Anhui, China', country: 'China', moqKg: 1000, leadTimeDays: 14, costPerKg: 0.95, certifications: ['ISO 22000', 'FDA GRAS', 'Kosher'], reliability: 0.95, inStock: true },
      { name: 'Jungbunzlauer', location: 'Vienna, Austria', country: 'Singapore', moqKg: 500, leadTimeDays: 21, costPerKg: 1.20, certifications: ['ISO 22000', 'Organic'], reliability: 0.98, inStock: true },
    ],
    substitutes: ['ACD_002', 'ACD_003'],
    regulatoryStatus: { fda: 'approved', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },
  {
    id: 'ACD_002',
    name: 'Phosphoric Acid 85%',
    nameChinese: '磷酸 85%',
    category: 'acidulant',
    function: ['acidulation', 'tartness', 'buffer-capacity'],
    properties: {
      solubility: 'water-soluble',
      pHStabilityMin: 2.0,
      pHStabilityMax: 5.0,
      heatSensitivity: 'low',
      maxProcessingTemp: 150,
      storageTemp: 'Cool & Dry',
      shelfLifeMonths: 24,
      caloriesPer100g: 0,
      proteinPer100g: 0,
      sugarPer100g: 0,
    },
    suppliers: [
      { name: 'Prayon', location: 'Engis, Belgium', country: 'Singapore', moqKg: 200, leadTimeDays: 14, costPerKg: 1.80, certifications: ['ISO 22000', 'FDA GRAS', 'EU Food Grade'], reliability: 0.97, inStock: true },
    ],
    substitutes: ['ACD_001'],
    regulatoryStatus: { fda: 'approved', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },

  // ===== STABILIZERS =====
  {
    id: 'STB_001',
    name: 'Xanthan Gum',
    nameChinese: '黄原胶',
    category: 'stabilizer',
    function: ['viscosity-control', 'suspension', 'stabilization'],
    properties: {
      solubility: 'water-soluble',
      pHStabilityMin: 3.0,
      pHStabilityMax: 9.0,
      heatSensitivity: 'low',
      maxProcessingTemp: 120,
      storageTemp: 'Cool & Dry',
      shelfLifeMonths: 24,
      caloriesPer100g: 0,
      proteinPer100g: 0,
      sugarPer100g: 0,
    },
    suppliers: [
      { name: 'CP Kelco', location: 'Atlanta, USA', country: 'Singapore', moqKg: 50, leadTimeDays: 14, costPerKg: 12.80, certifications: ['ISO 22000', 'FDA GRAS', 'Organic'], reliability: 0.98, inStock: true },
      { name: 'Jungbunzlauer', location: 'Vienna, Austria', country: 'Singapore', moqKg: 100, leadTimeDays: 21, costPerKg: 11.50, certifications: ['ISO 22000', 'Kosher', 'Halal'], reliability: 0.96, inStock: true },
    ],
    substitutes: ['STB_002', 'STB_003'],
    regulatoryStatus: { fda: 'approved', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },
  {
    id: 'STB_002',
    name: 'Sodium CMC (Low Substitution)',
    nameChinese: '低取代度羧甲基纤维素钠',
    category: 'stabilizer',
    function: ['thickening', 'protein-stabilization', 'suspension'],
    properties: {
      solubility: 'water-soluble',
      pHStabilityMin: 4.0,
      pHStabilityMax: 10.0,
      heatSensitivity: 'low',
      maxProcessingTemp: 150,
      storageTemp: 'Cool & Dry',
      shelfLifeMonths: 24,
      caloriesPer100g: 0,
      proteinPer100g: 0,
      sugarPer100g: 0,
    },
    suppliers: [
      { name: 'Ashland', location: 'Delaware, USA', country: 'Singapore', moqKg: 100, leadTimeDays: 14, costPerKg: 8.50, certifications: ['ISO 22000', 'FDA GRAS'], reliability: 0.97, inStock: true },
    ],
    substitutes: ['STB_001', 'STB_003'],
    regulatoryStatus: { fda: 'approved', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },
  {
    id: 'STB_003',
    name: 'Kappa Carrageenan',
    nameChinese: '卡拉胶',
    category: 'stabilizer',
    function: ['gelation', 'protein-stabilization', 'texture'],
    properties: {
      solubility: 'water-soluble',
      pHStabilityMin: 4.0,
      pHStabilityMax: 9.0,
      heatSensitivity: 'medium',
      maxProcessingTemp: 85,
      storageTemp: 'Cool & Dry',
      shelfLifeMonths: 18,
      caloriesPer100g: 0,
      proteinPer100g: 0,
      sugarPer100g: 0,
    },
    suppliers: [
      { name: 'FMC Biopolymer', location: 'Philadelphia, USA', country: 'Singapore', moqKg: 50, leadTimeDays: 21, costPerKg: 15.60, certifications: ['ISO 22000', 'FDA GRAS', 'Organic'], reliability: 0.96, inStock: true },
    ],
    substitutes: ['STB_001', 'STB_002'],
    regulatoryStatus: { fda: 'approved', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },

  // ===== VITAMINS & MINERALS =====
  {
    id: 'VIT_001',
    name: 'Vitamin C (Ascorbic Acid)',
    nameChinese: '维生素C',
    category: 'vitamin-mineral',
    function: ['antioxidant', 'vitamin-fortification', 'preservation'],
    properties: {
      solubility: 'water-soluble',
      pHStabilityMin: 2.0,
      pHStabilityMax: 6.0,
      heatSensitivity: 'high',
      maxProcessingTemp: 75,
      storageTemp: 'Cool & Dry (<15°C)',
      shelfLifeMonths: 24,
      caloriesPer100g: 0,
      proteinPer100g: 0,
      sugarPer100g: 0,
    },
    suppliers: [
      { name: 'DSM', location: 'Basel, Switzerland', country: 'Singapore', moqKg: 25, leadTimeDays: 14, costPerKg: 12.50, certifications: ['ISO 22000', 'FDA GRAS', 'USP'], reliability: 0.99, inStock: true },
      { name: 'BASF', location: 'Ludwigshafen, Germany', country: 'Singapore', moqKg: 50, leadTimeDays: 21, costPerKg: 11.80, certifications: ['ISO 22000', 'FDA GRAS'], reliability: 0.98, inStock: true },
    ],
    substitutes: [],
    regulatoryStatus: { fda: 'approved', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },
  {
    id: 'VIT_002',
    name: 'Vitamin B Complex',
    nameChinese: '维生素B族',
    category: 'vitamin-mineral',
    function: ['vitamin-fortification', 'energy-metabolism'],
    properties: {
      solubility: 'water-soluble',
      pHStabilityMin: 3.5,
      pHStabilityMax: 6.5,
      heatSensitivity: 'medium',
      maxProcessingTemp: 85,
      storageTemp: 'Cool & Dry (<25°C)',
      shelfLifeMonths: 18,
      caloriesPer100g: 0,
      proteinPer100g: 0,
      sugarPer100g: 0,
    },
    suppliers: [
      { name: 'DSM', location: 'Basel, Switzerland', country: 'Singapore', moqKg: 10, leadTimeDays: 14, costPerKg: 85.00, certifications: ['ISO 22000', 'FDA GRAS', 'USP'], reliability: 0.99, inStock: true },
    ],
    substitutes: [],
    regulatoryStatus: { fda: 'approved', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },
  {
    id: 'VIT_003',
    name: 'Vitamin D3 (Cholecalciferol)',
    nameChinese: '维生素D3',
    category: 'vitamin-mineral',
    function: ['vitamin-fortification', 'bone-health'],
    properties: {
      solubility: 'fat-soluble',
      pHStabilityMin: 3.0,
      pHStabilityMax: 8.0,
      heatSensitivity: 'medium',
      maxProcessingTemp: 100,
      storageTemp: 'Cool & Dry (<15°C)',
      shelfLifeMonths: 24,
      caloriesPer100g: 0,
      proteinPer100g: 0,
      sugarPer100g: 0,
    },
    suppliers: [
      { name: 'DSM', location: 'Basel, Switzerland', country: 'Singapore', moqKg: 1, leadTimeDays: 14, costPerKg: 2500.00, certifications: ['ISO 22000', 'FDA GRAS', 'USP'], reliability: 0.99, inStock: true },
    ],
    substitutes: [],
    regulatoryStatus: { fda: 'approved', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },

  // ===== FUNCTIONAL ADDITIVES =====
  {
    id: 'FNC_001',
    name: 'L-Theanine',
    nameChinese: '茶氨酸',
    category: 'functional-additive',
    function: ['calming', 'focus-enhancement', 'amino-acid'],
    properties: {
      solubility: 'water-soluble',
      pHStabilityMin: 3.0,
      pHStabilityMax: 8.0,
      heatSensitivity: 'low',
      maxProcessingTemp: 150,
      storageTemp: 'Cool & Dry',
      shelfLifeMonths: 36,
      caloriesPer100g: 0,
      proteinPer100g: 0,
      sugarPer100g: 0,
    },
    suppliers: [
      { name: 'Taiyo Kagaku', location: 'Yokkaichi, Japan', country: 'Japan', moqKg: 5, leadTimeDays: 14, costPerKg: 280.00, certifications: ['ISO 22000', 'FDA GRAS', 'Japanese FSA'], reliability: 0.98, inStock: true },
      { name: 'Beijing Tianmai', location: 'Beijing, China', country: 'China', moqKg: 10, leadTimeDays: 21, costPerKg: 220.00, certifications: ['ISO 22000', 'FDA GRAS'], reliability: 0.92, inStock: true },
    ],
    substitutes: [],
    regulatoryStatus: { fda: 'gras', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },
  {
    id: 'FNC_002',
    name: 'Caffeine Anhydrous',
    nameChinese: '无水咖啡因',
    category: 'functional-additive',
    function: ['stimulant', ' alertness', 'energy-boost'],
    properties: {
      solubility: 'water-soluble',
      pHStabilityMin: 2.0,
      pHStabilityMax: 8.0,
      heatSensitivity: 'low',
      maxProcessingTemp: 150,
      storageTemp: 'Cool & Dry',
      shelfLifeMonths: 60,
      caloriesPer100g: 0,
      proteinPer100g: 0,
      sugarPer100g: 0,
    },
    suppliers: [
      { name: 'BASF', location: 'Ludwigshafen, Germany', country: 'Singapore', moqKg: 25, leadTimeDays: 14, costPerKg: 45.00, certifications: ['ISO 22000', 'FDA GRAS', 'USP'], reliability: 0.99, inStock: true },
      { name: 'Kraft Chemical', location: 'Illinois, USA', country: 'Singapore', moqKg: 50, leadTimeDays: 21, costPerKg: 42.00, certifications: ['ISO 22000', 'FDA GRAS'], reliability: 0.96, inStock: true },
    ],
    substitutes: [],
    regulatoryStatus: { fda: 'approved', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },
  {
    id: 'FNC_003',
    name: 'Taurine',
    nameChinese: '牛磺酸',
    category: 'functional-additive',
    function: ['energy-support', 'hydration', 'amino-acid'],
    properties: {
      solubility: 'water-soluble',
      pHStabilityMin: 3.0,
      pHStabilityMax: 8.0,
      heatSensitivity: 'low',
      maxProcessingTemp: 150,
      storageTemp: 'Cool & Dry',
      shelfLifeMonths: 36,
      caloriesPer100g: 0,
      proteinPer100g: 0,
      sugarPer100g: 0,
    },
    suppliers: [
      { name: 'Grand Pharma', location: 'Wuhan, China', country: 'China', moqKg: 100, leadTimeDays: 14, costPerKg: 8.50, certifications: ['ISO 22000', 'FDA GRAS', 'Kosher'], reliability: 0.95, inStock: true },
      { name: 'Ningbo JHK', location: 'Ningbo, China', country: 'China', moqKg: 200, leadTimeDays: 21, costPerKg: 7.80, certifications: ['ISO 22000', 'FDA GRAS'], reliability: 0.90, inStock: true },
    ],
    substitutes: [],
    regulatoryStatus: { fda: 'approved', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },

  // ===== FLAVOR SYSTEMS =====
  {
    id: 'FLV_001',
    name: 'Natural Green Tea Flavor',
    nameChinese: '天然绿茶香精',
    category: 'flavor-system',
    function: ['flavoring', 'aroma-enhancement'],
    properties: {
      solubility: 'alcohol-soluble',
      pHStabilityMin: 3.0,
      pHStabilityMax: 6.0,
      heatSensitivity: 'medium',
      maxProcessingTemp: 85,
      storageTemp: 'Cool & Dark (4-10°C)',
      shelfLifeMonths: 12,
      caloriesPer100g: 0,
      proteinPer100g: 0,
      sugarPer100g: 0,
    },
    suppliers: [
      { name: 'Kerry', location: 'County Kerry, Ireland', country: 'Singapore', moqKg: 10, leadTimeDays: 21, costPerKg: 85.00, certifications: ['ISO 22000', 'FSSC 22000'], reliability: 0.98, inStock: true },
      { name: 'Takasago', location: 'Tokyo, Japan', country: 'Japan', moqKg: 5, leadTimeDays: 14, costPerKg: 120.00, certifications: ['ISO 22000', 'JAS Organic'], reliability: 0.97, inStock: true },
    ],
    substitutes: ['FLV_002'],
    regulatoryStatus: { fda: 'approved', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },
  {
    id: 'FLV_002',
    name: 'Natural Yuzu Citrus Flavor',
    nameChinese: '天然柚子柑橘香精',
    category: 'flavor-system',
    function: ['flavoring', 'aroma-enhancement', 'refreshing-note'],
    properties: {
      solubility: 'alcohol-soluble',
      pHStabilityMin: 2.5,
      pHStabilityMax: 5.5,
      heatSensitivity: 'high',
      maxProcessingTemp: 70,
      storageTemp: 'Cool & Dark (4-10°C)',
      shelfLifeMonths: 12,
      caloriesPer100g: 0,
      proteinPer100g: 0,
      sugarPer100g: 0,
    },
    suppliers: [
      { name: 'Sensient Flavors', location: 'St. Louis, USA', country: 'Singapore', moqKg: 5, leadTimeDays: 21, costPerKg: 150.00, certifications: ['ISO 22000', 'FSSC 22000'], reliability: 0.96, inStock: true },
    ],
    substitutes: ['FLV_003'],
    regulatoryStatus: { fda: 'approved', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },
  {
    id: 'FLV_003',
    name: 'Natural Mango Passion Fruit Flavor',
    nameChinese: '天然芒果百香果香精',
    category: 'flavor-system',
    function: ['flavoring', 'tropical-note', 'aroma-enhancement'],
    properties: {
      solubility: 'alcohol-soluble',
      pHStabilityMin: 3.0,
      pHStabilityMax: 6.0,
      heatSensitivity: 'high',
      maxProcessingTemp: 75,
      storageTemp: 'Cool & Dark (4-10°C)',
      shelfLifeMonths: 12,
      caloriesPer100g: 0,
      proteinPer100g: 0,
      sugarPer100g: 0,
    },
    suppliers: [
      { name: 'Givaudan', location: 'Geneva, Switzerland', country: 'Singapore', moqKg: 10, leadTimeDays: 21, costPerKg: 95.00, certifications: ['ISO 22000', 'FSSC 22000', 'Halal'], reliability: 0.98, inStock: true },
    ],
    substitutes: ['FLV_002'],
    regulatoryStatus: { fda: 'approved', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },

  // ===== PRESERVATIVES =====
  {
    id: 'PRS_001',
    name: 'Potassium Sorbate',
    nameChinese: '山梨酸钾',
    category: 'preservative',
    function: ['antimicrobial', 'preservation', 'shelf-life-extension'],
    properties: {
      solubility: 'water-soluble',
      pHStabilityMin: 2.0,
      pHStabilityMax: 6.5,
      heatSensitivity: 'low',
      maxProcessingTemp: 150,
      storageTemp: 'Cool & Dry',
      shelfLifeMonths: 36,
      caloriesPer100g: 0,
      proteinPer100g: 0,
      sugarPer100g: 0,
    },
    suppliers: [
      { name: 'Lianyungang SS', location: 'Jiangsu, China', country: 'China', moqKg: 200, leadTimeDays: 14, costPerKg: 4.20, certifications: ['ISO 22000', 'FDA GRAS', 'Kosher'], reliability: 0.94, inStock: true },
    ],
    substitutes: ['PRS_002'],
    regulatoryStatus: { fda: 'approved', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },

  // ===== ALOE & FUNCTIONAL EXTRACTS =====
  {
    id: 'ALO_001',
    name: 'Aloe Vera Juice 2x Concentrate',
    nameChinese: '芦荟汁 2倍浓缩液',
    category: 'functional-additive',
    function: ['functional-benefit', 'hydration', 'natural-source'],
    properties: {
      solubility: 'water-soluble',
      pHStabilityMin: 3.5,
      pHStabilityMax: 5.0,
      heatSensitivity: 'high',
      maxProcessingTemp: 75,
      storageTemp: 'Chilled (2-8°C)',
      shelfLifeMonths: 6,
      caloriesPer100g: 12,
      proteinPer100g: 0,
      sugarPer100g: 2.5,
    },
    suppliers: [
      { name: 'Aloe Laboratories', location: 'Texas, USA', country: 'Singapore', moqKg: 100, leadTimeDays: 21, costPerKg: 6.50, certifications: ['ISO 22000', 'USDA Organic', 'IASC Certified'], reliability: 0.95, inStock: true },
    ],
    substitutes: ['COC_001'],
    regulatoryStatus: { fda: 'approved', efsa: 'approved', chinaGB: 'approved' },
    allergens: [],
  },
];

// Create a Map for quick lookup
export const INGREDIENT_DATABASE = new Map<string, Ingredient>(
  ASIAN_RTD_INGREDIENTS.map(ing => [ing.id, ing])
);

// Helper functions for database operations
export function getIngredientById(id: string): Ingredient | undefined {
  return INGREDIENT_DATABASE.get(id);
}

export function getIngredientsByCategory(category: string): Ingredient[] {
  return ASIAN_RTD_INGREDIENTS.filter(ing => ing.category === category);
}

export function getSubstitutes(ingredientId: string): Ingredient[] {
  const ingredient = INGREDIENT_DATABASE.get(ingredientId);
  if (!ingredient) return [];
  return ingredient.substitutes
    .map(id => INGREDIENT_DATABASE.get(id))
    .filter((ing): ing is Ingredient => ing !== undefined);
}

export function searchIngredients(query: string): Ingredient[] {
  const lowerQuery = query.toLowerCase();
  return ASIAN_RTD_INGREDIENTS.filter(ing =>
    ing.name.toLowerCase().includes(lowerQuery) ||
    ing.nameChinese?.includes(query) ||
    ing.category.toLowerCase().includes(lowerQuery)
  );
}
